sudo: enabled
language: node_js
node_js:
  - '12'
services:
  - docker
os:
- linux
env:
  global:
    - DOCKER_USERNAME=juliocas
    - DOCKER_IMAGE_NAME=risk-management
    - K8S_DEPLOYMENT_NAME=risk-management-deployment
notifications:
  email:
    recipients:
      - juliocas65@gmail.com
    on_success: always
    on_failure: always
before_script:
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.7.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  - docker pull ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
  - npm run test:unit
  - npm run test:cov
  - npm run lint
  - echo $TRAVIS_BUILD_DIR
  - echo $DOCKER_USERNAME
  - echo $DOCKER_IMAGE_NAME
  - echo $K8S_DEPLOYMENT_NAME
  - docker run -v ${TRAVIS_BUILD_DIR}:/public ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_IMAGE_NAME} /public
after_script:
  - docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} Dockerfile .
  - docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
  - docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
  - docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
  - sed -i -e 's|KUBE_CA_CERT|'"${KUBE_CA_CERT}"'|g' kubeconfig
  - sed -i -e 's|KUBE_ENDPOINT|'"${KUBE_ENDPOINT}"'|g' kubeconfig
  - sed -i -e 's|KUBE_ADMIN_CERT|'"${KUBE_ADMIN_CERT}"'|g' kubeconfig
  - sed -i -e 's|KUBE_ADMIN_KEY|'"${KUBE_ADMIN_KEY}"'|g' kubeconfig
  - sed -i -e 's|KUBE_USERNAME|'"${KUBE_USERNAME}"'|g' kubeconfig
  - echo kubeconfig
  - docker run -v ${TRAVIS_BUILD_DIR}:/kube kubectl --kubeconfig /kube/kubeconfig set image deployment/${K8S_DEPLOYMENT_NAME} ${K8S_DEPLOYMENT_NAME}=${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:$TRAVIS_BUILD_ID
