---
apiVersion: v1
kind: Namespace
metadata:
  name: risk-management
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: risk-management
  name: risk-management-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: risk-management-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: risk-management-app
  replicas: 3
    spec:
      containers:
      - image: risk-management
        imagePullPolicy: Always
        name: risk-management-app
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  namespace: risk-management
  name: risk-management-service
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: risk-management-app
---
apiVersion: v1
kind: Ingress
metadata:
  namespace: risk-management
  name: risk-management-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: risk-management-service
              servicePort: 3000