apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: risk-management
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: risk-management
rules:
  - apiGroups: ["", "apps", "batch", "extensions"]
    resources: ["deployments", "services", "replicasets", "pods", "jobs", "cronjobs"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default
  namespace: risk-management
subjects:
  - kind: ServiceAccount
    name: default
    namespace: risk-management
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io